In [21]:
import torch
import torch.nn as nn

In [22]:
#define input and output layers
class firstNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        # This model has no layers
    def forward(self,x):
        return x
    #doesnot do forward propapagtion
    

In [7]:
#define the model
# creating your model object
model = firstNeuralNetwork()

In [8]:

print(model)

firstNeuralNetwork()


In [24]:
#tensor data with 100 rows and 5 columns
t = torch.randn(10, 5)
print(t.shape)
print(t.dtype)
print(t.size)
print(t)


torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7fac25c5b880>
tensor([[-0.1073, -0.5062,  0.7803,  1.2448, -0.0524],
        [-0.2641,  1.8127, -0.5284,  0.6581, -0.3241],
        [ 1.2093, -1.7364,  0.9000, -1.7362,  1.2088],
        [-0.4740,  2.1311, -0.7420, -1.2711, -0.4354],
        [ 1.2478, -0.5698, -0.3619,  0.2996,  0.5381],
        [ 0.0839,  0.7248,  0.0523,  0.8430,  0.1183],
        [ 0.6047,  2.2503,  0.4626, -0.2397,  0.6945],
        [ 0.8742, -1.1833, -0.4156, -0.3262,  0.3995],
        [-0.0209,  0.7138, -0.6352,  0.8820,  0.6549],
        [-2.3602, -2.3418, -0.8072,  1.9783,  0.4985]])


In [25]:
#pass the tensor data to the model
print(model(t))

tensor([[-0.1073, -0.5062,  0.7803,  1.2448, -0.0524],
        [-0.2641,  1.8127, -0.5284,  0.6581, -0.3241],
        [ 1.2093, -1.7364,  0.9000, -1.7362,  1.2088],
        [-0.4740,  2.1311, -0.7420, -1.2711, -0.4354],
        [ 1.2478, -0.5698, -0.3619,  0.2996,  0.5381],
        [ 0.0839,  0.7248,  0.0523,  0.8430,  0.1183],
        [ 0.6047,  2.2503,  0.4626, -0.2397,  0.6945],
        [ 0.8742, -1.1833, -0.4156, -0.3262,  0.3995],
        [-0.0209,  0.7138, -0.6352,  0.8820,  0.6549],
        [-2.3602, -2.3418, -0.8072,  1.9783,  0.4985]])


In [11]:
nn = model(t)
print(nn)

tensor([[-0.0747, -0.3688,  0.9659, -0.4063,  0.1968],
        [-1.4978,  0.7340, -0.8227, -1.6951, -1.4528],
        [-0.3080,  0.5014, -0.9325, -0.0522,  0.7317],
        [-0.3406, -1.5538,  0.1305,  0.0844,  0.7142],
        [-0.4699, -0.4154, -0.7419,  0.1930, -1.4290],
        [-0.9178,  0.0076, -1.3301, -0.1555, -0.6332],
        [ 1.6774, -0.2842, -1.8248, -0.5023,  0.6216],
        [ 1.3678,  0.8395,  0.0491,  1.3597, -0.8733],
        [-0.7917,  1.3721, -1.5254,  2.5420, -0.3379],
        [ 0.3584, -0.8067, -1.0862, -2.5868,  0.4965]])


In [15]:

print(nn.size)

<built-in method size of Tensor object at 0x7fac2668c220>


In [16]:
print(nn.shape)

torch.Size([10, 5])


In [33]:
#create  layers to handle and process data
class firstNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        #Applies a linear transformation to the incoming data: y=xAT+by=xAT+b
        #nn.Linear(input_dimension,outout_dimension)
        #binary outout
        self.linear0 = nn.Linear(5,2)
        
    def forward(self,x):
        x = self.linear0(x)
        print(x.shape)
        return x

In [34]:
model = firstNeuralNetwork()
print(model(t))


torch.Size([10, 2])
tensor([[-0.7261, -0.8761],
        [-0.7690,  0.2447],
        [-0.3245, -0.0120],
        [-0.1393,  0.7865],
        [-0.7020,  0.0954],
        [-0.9058, -0.1204],
        [-1.5245,  0.6703],
        [-0.1604, -0.0195],
        [-0.9042,  0.2021],
        [ 0.4425, -1.3407]], grad_fn=<AddmmBackward0>)


In [50]:
class firstNeuralNeetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(5,4)
        self.linear1 = nn.Linear(4,2)
    def forward(self,x):
        x = self.linear0(x)
        print(x.shape)
        x = self.linear1(x)
        print(x.shape)
        return x

In [51]:
model = firstNeuralNeetwork()
t = torch.randn(10, 5)
n = model(t)

torch.Size([10, 4])
torch.Size([10, 2])


just changing columns size

In [58]:
#create versious hidden layers
class firstNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(5,4)
        self.linear1 = nn.Linear(4,3)
        self.linear2 = nn.Linear(3,2)
    def forward(self,x):
        x = self.linear0(x)
        print(x.shape)
        x = self.linear1(x)
        print(x.shape)
        x = self.linear2(x)
        print(x.shape)
        return x

In [59]:
module = firstNeuralNetwork()
t = torch.randn(10,5)
n = module(t)

torch.Size([10, 4])
torch.Size([10, 3])
torch.Size([10, 2])


In [82]:
module = firstNeuralNetworkModel()
t = torch.randn(10,5)
n = module(t)

torch.Size([10, 100])
torch.Size([10, 3])
torch.Size([10, 2])


In [93]:
#complex hidden layer
class firstNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(5,4)
        self.linear1 = nn.Linear(4,3)
        self.linear2 = nn.Linear(4,2)
    def forward(self,x):
        x1 = self.linear0(x)
        print(x1.shape)
        x2 = self.linear1(x1)
        print(x2.shape)
        x3 = self.linear2(x1)
        print(x3.shape)
        return x

In [94]:
module = firstNeuralNetwork()
t = torch.randn(10,5)
n = module(t)

torch.Size([10, 4])
torch.Size([10, 3])
torch.Size([10, 2])


In [88]:
t.shape

torch.Size([10, 5])

In [95]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/prodramp/publiccode/master/datasets/heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [104]:
df_input = pd.DataFrame(df.iloc[:, 0:-1])
df_target = pd.DataFrame(df.iloc[:,-1],columns=['target'])

In [105]:
df_input.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [106]:
df_target.head()

target
0       1
1       1
2       1
3       1
4       1

In [107]:
input_array = df_input.to_numpy()
target_array = df_target.to_numpy()

In [108]:
inputs = torch.from_numpy(np.array(input_array,dtype='float32'))
targets = torch.from_numpy(np.array(target_array,dtype='float32'))

In [109]:
inputs.shape

torch.Size([303, 13])

In [110]:
targets.shape

torch.Size([303, 1])

In [116]:
class Neural_network_dataDiesease(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(13,50)
        self.linear1 = nn.Linear(50,9)
        self.linear2 = nn.Linear(9,7)
        self.linear3 = nn.Linear(7,2)
    def forward(self,x):
        x1 = self.linear0(x)
        print(x1.shape)
        x2 = self.linear1(x1)
        print(x2.shape)
        x3 = self.linear2(x2)
        print(x3.shape)
        x4 = self.linear3(x3)
        print(x4.shape)
        return x
        

In [117]:
model = Neural_network_dataDiesease()
n = model(inputs)

torch.Size([303, 50])
torch.Size([303, 9])
torch.Size([303, 7])
torch.Size([303, 2])
