# n-dimension array

In [1]:
import torch

single dimension torch

In [3]:
torch.Tensor([1,2,3,4,5])

tensor([1., 2., 3., 4., 5.])

2 dimenstion torch

In [5]:
torch.Tensor([[1,2,3,4],[4,5,6,7]])

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])

In [6]:
t = torch.Tensor([1,2,3,4,5])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)
     

tensor([1., 2., 3., 4., 5.])
torch.Size([5])
<class 'torch.Tensor'>
torch.float32


In [7]:
t = torch.Tensor([[1,2,3,4],[4,5,6,7]])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)
     

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.Size([2, 4])
<class 'torch.Tensor'>
torch.float32


In [11]:
t = torch.Tensor([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)
     

tensor([[[1., 2., 3., 4.],
         [4., 5., 6., 7.]],

        [[1., 2., 3., 4.],
         [4., 5., 6., 7.]]])
torch.Size([2, 2, 4])
<class 'torch.Tensor'>
torch.float32


In [12]:
t = torch.Tensor([[[1,2,3,4],[4,5,6,7],[4,5,6,7]],[[1,2,3,4],[4,5,6,7],[4,5,6,7]]])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)

tensor([[[1., 2., 3., 4.],
         [4., 5., 6., 7.],
         [4., 5., 6., 7.]],

        [[1., 2., 3., 4.],
         [4., 5., 6., 7.],
         [4., 5., 6., 7.]]])
torch.Size([2, 3, 4])
<class 'torch.Tensor'>
torch.float32


# using torch zeros

In [16]:
t = torch.zeros(1,3,dtype=torch.int32)
t

tensor([[0, 0, 0]], dtype=torch.int32)

In [17]:
t = torch.zeros(1,3,dtype=torch.float)
t

tensor([[0., 0., 0.]])

In [18]:
t = torch.zeros(2,1,8,dtype=torch.int)
t

tensor([[[0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0]]], dtype=torch.int32)

In [19]:
t = torch.zeros(5,dtype=torch.int32)
t

tensor([0, 0, 0, 0, 0], dtype=torch.int32)

In [20]:
t = torch.zeros(2,3,dtype=torch.int32)
t

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

# using torch ones

In [21]:
t = torch.ones(5,dtype=torch.int32)
t

tensor([1, 1, 1, 1, 1], dtype=torch.int32)

In [27]:
t = torch.ones(5,1,dtype=torch.int32)
t

tensor([[1],
        [1],
        [1],
        [1],
        [1]], dtype=torch.int32)

In [28]:
t = torch.ones(5,3,dtype=torch.int32)
t

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [29]:
t = torch.ones(2,5,1,dtype=torch.int32)
t

tensor([[[1],
         [1],
         [1],
         [1],
         [1]],

        [[1],
         [1],
         [1],
         [1],
         [1]]], dtype=torch.int32)

In [30]:
t = torch.ones(3,3,dtype=torch.int32)
t

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [32]:
t = torch.ones(3,5,2,dtype=torch.int32)
t

tensor([[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]], dtype=torch.int32)

In [33]:
#create 5 different section with 5 rows and 3 columns of zeros
t = torch.zeros(5,5,3,dtype=torch.float)
t

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [34]:
t[0]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
t[0][0]

tensor([0., 0., 0.])

# using randn

In [39]:
torch.randn(2,8)

tensor([[-0.2137, -2.1477, -1.0745,  0.2168, -0.0739, -1.1044,  0.4381, -0.2959],
        [ 1.0053, -0.4011, -0.7459, -0.4087,  0.9665, -1.0964,  1.2508, -1.0118]])

# using zero_like

In [41]:
t = torch.randn(2,8)
t_zeros = torch.zeros_like(t)
print(t_zeros)
print(t_zeros.dtype)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
torch.float32


In [43]:
t = torch.ones(2,4,2,dtype = torch.float)
randn_ones = torch.randn_like(t)
print(randn_ones)

tensor([[[ 1.2831,  0.9819],
         [-0.3122, -0.9528],
         [ 0.8686, -0.9155],
         [ 1.5269,  0.9751]],

        [[-1.7300, -0.4142],
         [ 0.1657,  0.3069],
         [-0.1560, -1.6249],
         [ 0.3450,  0.5324]]])


# converting tensor to numpy array

In [45]:
t = torch.ones(2,4,2,dtype = torch.float)
new_t = t.numpy()
new_t

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)

In [47]:
print(type(new_t))
print(new_t.dtype)

<class 'numpy.ndarray'>
float32


# Tensor operation <br/>  Muliplication

In [63]:
a = torch.randn(3,2)
b = torch.randn(2,4)
result = a.mm(b)
print(result)
print(type(result))
print(result.dtype)

tensor([[ 2.5635,  1.4991, -2.2707,  1.7203],
        [-1.6274,  0.5256,  1.1328, -0.9982],
        [-2.7853, -0.0488,  2.1370, -1.7687]])
<class 'torch.Tensor'>
torch.float32


# Transpose

In [65]:
print(result.shape)
nn  = result.T
print(nn.shape)

torch.Size([3, 4])
torch.Size([4, 3])


# Arithmetic operation

In [67]:
#   +
a = torch.ones(1,5)
result = a+5
print(result)

tensor([[6., 6., 6., 6., 6.]])


In [68]:
#   +
a = torch.ones(2,5)
result = a+5
print(result)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])


In [71]:
#   +
a = torch.zeros(2,2,5)
result = a+3
print(result)

tensor([[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])


In [73]:
#   x
a = torch.ones(1,5)
print(a)
result = a * 1.5
print(result)

tensor([[1., 1., 1., 1., 1.]])
tensor([[1.5000, 1.5000, 1.5000, 1.5000, 1.5000]])


In [75]:
#   /
a = torch.randn(1,5)
print(a)
result = a / 0.5
print(result)

tensor([[ 1.6761,  1.4341, -0.0360, -0.8877,  1.6057]])
tensor([[ 3.3523,  2.8682, -0.0721, -1.7755,  3.2114]])


In [76]:
#   -
a = torch.randn(1,5)
print(a)
result = a - 0.5
print(result)

tensor([[ 1.8162,  0.5454, -0.8737, -0.0584,  0.6366]])
tensor([[ 1.3162,  0.0454, -1.3737, -0.5584,  0.1366]])


# square root

In [79]:
a = torch.randn(1,4)
print(a)
t = a**2
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[ 0.5291,  1.0529,  0.1603, -1.0637]])
tensor([[0.2800, 1.1087, 0.0257, 1.1314]])
<class 'torch.Tensor'>
torch.Size([1, 4])
torch.Size([1, 4])
torch.float32


# aggregation

In [82]:
n = torch.rand(3,2)
print(n)
agg = n.sum()
agg_item  = agg.item()
print(agg_item, type(agg_item))

tensor([[0.4915, 0.0980],
        [0.9416, 0.4720],
        [0.9126, 0.9448]])
3.860412120819092 <class 'float'>


# in place operators

In [84]:

tensor = torch.rand(2,2)
print(f"{tensor} \n")

tensor.mul_(5)
print(tensor)

tensor([[0.0628, 0.7607],
        [0.6215, 0.1980]]) 

tensor([[0.3139, 3.8035],
        [3.1077, 0.9898]])


In [86]:
tensor = torch.rand(2,2)
print(f"{tensor} \n")
tensor.add_(2)
print(tensor)

tensor([[0.6036, 0.3889],
        [0.2631, 0.1775]]) 

tensor([[2.6036, 2.3889],
        [2.2631, 2.1775]])


In [87]:
tensor = torch.rand(2,2)
print(f"{tensor} \n")
tensor.sub_(0.5)
print(tensor)

tensor([[0.1349, 0.3014],
        [0.5395, 0.8816]]) 

tensor([[-0.3651, -0.1986],
        [ 0.0395,  0.3816]])


In [88]:
tensor = torch.rand(2,2)
print(f"{tensor} \n")
tensor.div_(0.3)
print(tensor)

tensor([[0.3638, 0.6401],
        [0.8237, 0.6210]]) 

tensor([[1.2128, 2.1336],
        [2.7457, 2.0701]])


# Logical Operation

In [89]:
A = torch.Tensor([[1,2,3], [4,5,6]])
print(A)
t = A >=5 
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[False, False, False],
        [False,  True,  True]])
<class 'torch.Tensor'>
torch.Size([2, 3])
torch.Size([2, 3])
torch.bool


# indexing and slicing

In [92]:
#tensor = torch.ones(4, 4)
tensor = torch.rand(4, 4)
print(f"Full Tensor:\n {tensor}")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Second column: {tensor[:, 1]}")
print(f"Last column: {tensor[..., -1]}")


Full Tensor:
 tensor([[0.7114, 0.9239, 0.7493, 0.3020],
        [0.7567, 0.5788, 0.0036, 0.0816],
        [0.4148, 0.5402, 0.2348, 0.5726],
        [0.6661, 0.2076, 0.1152, 0.2482]])
First row: tensor([0.7114, 0.9239, 0.7493, 0.3020])
First column: tensor([0.7114, 0.7567, 0.4148, 0.6661])
Second column: tensor([0.9239, 0.5788, 0.5402, 0.2076])
Last column: tensor([0.3020, 0.0816, 0.5726, 0.2482])


In [93]:
# all rows and  starting  take last 2 columns 
tensor[:,2:]

tensor([[0.7493, 0.3020],
        [0.0036, 0.0816],
        [0.2348, 0.5726],
        [0.1152, 0.2482]])

# Tensor Reshape Operation

In [94]:
t = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(t)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [95]:
print(t.shape)

torch.Size([3, 2])


In [96]:
#reshape 2 rows and 3 columns
print(t.view(2, 3))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [100]:
#reshape -1 any number 
print(t.view(-1,3))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [102]:
print(t.view(3,-1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [108]:
print(t.view(2,3))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [109]:
print(t.view(-1,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [110]:
print(t.view(6,-1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [111]:
print(t.view(-1,6))

tensor([[1, 2, 3, 4, 5, 6]])


# Tensor Concatnation:

In [118]:
t = torch.ones(2,2,)
t0 = torch.rand(2,2)



t1 = torch.cat([t, t, t0])
t2 = torch.cat([t, t, t0], dim=1)
print(t1)
print(t1.shape,"\n")
print(t2)
print(t2.shape)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.8647, 0.7245],
        [0.9808, 0.2153]])
torch.Size([6, 2]) 

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 0.8647, 0.7245],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.9808, 0.2153]])
torch.Size([2, 6])


# Device for tensors

In [120]:
shape = (2,3)
t = torch.ones(shape)
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Device tensor is stored on: cpu


# Cuda for torch

In [121]:
if torch.cuda.is_available():
    print(torch.cuda.device_count())

1


In [122]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [123]:
print(torch.cuda.device_count())

1


In [124]:
device=torch.device('cuda:0')
print(device)

cuda:0


In [125]:
cuda0 = torch.device('cuda:0')

In [126]:
shape = (2,3,)
t = torch.ones(shape, device=torch.device('cuda:0'))
#t = torch.ones(shape, device=torch.device(cuda0))
#t = torch.zeros(shape, device=torch.device(cuda0))
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
Device tensor is stored on: cuda:0


In [127]:
t = torch.rand(shape, device=torch.device(cuda0))
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[0.3906, 0.5608, 0.7207],
        [0.8679, 0.4039, 0.6949]], device='cuda:0')
Device tensor is stored on: cuda:0


# moving gpu to cpu

In [128]:
m1 = torch.ones(3, 2, device=cuda0)
m2 = torch.ones(3, 2, device=cuda0)
print(m1)
print(m2)
m0 = m1 + m2 
m0 = m0 * m0
print(m0)

m00 = m0.cpu()
print(m0)
print(m00)
print("-------------")
m0.cpu()
print(m0)
m0 = m0.cpu()
print(m0)
     


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
-------------
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
